model_kwargs:
  patch_size: 8
  image_size: 128
  n_classes: 41
  spec_encoder_kwargs:
    embed_dim: 384
    depth: 8
    num_heads: 6
    layer_scale: 0.0001
    pos_enc_sigma: 3
    n_queries: 8
    qkv_bias: true
    ffn_bias: true
    drop_path_rate: 0.
    proj_drop: 0.
    drop: 0.
    attn_drop: 0.
  spat_encoder_kwargs:
    model_name: timm/eva02_base_patch14_224.mim_in22k
    depth: 8
    model_kwargs:
      drop_rate: 0.
      pos_drop_rate: 0.
      patch_drop_rate: 0.
      proj_drop_rate: 0.
      attn_drop_rate: 0.
      drop_path_rate: 0.

data_kwargs:
  train_dataset:
    name: HSIRS
    root_dir: "/home/onishi/00_intern_prog/data/HSIRS_public"
    split: train
    split_seed: 42
    foreground_crop_probability: 0.8
    foreground_crop_seed: 42
    background_label: 0
  val_dataset:
    name: HSIRS
    root_dir: "/home/onishi/00_intern_prog/data/HSIRS_public"
    split: val
    split_seed: 42
  test_dataset:
    name: HSIRS
    root_dir: "/home/onishi/00_intern_prog/data/HSIRS_public"
    split: test
    split_seed: 42

training_kwargs:
  batch_size: 8
  evaluation_batch_size: 1
  num_workers: 12
  evaluation_num_workers: 8
  ssl_ckpt_path: carl_ssl_checkpoint.ckpt
  freeze_backbone: false
  monitor_metric: val_foreground_mIoU
  log_dir: logs/hsirs_seg_fine_tuning
  learning_rate: 1e-4
  random_resized_crop: false

metric_kwargs:
  background_label: 0

evaluation_kwargs:
  tile_size: 128
  tile_batch_size: 16

lightning_kwargs:
  max_epochs: 50
  accelerator: gpu
  devices: 1
  precision: bf16-mixed
  check_val_every_n_epoch: 5
  log_every_n_steps: 10
  enable_checkpointing: true
  num_sanity_val_steps: 0
  enable_progress_bar: true